// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAijz1FMDqvti9m4CWsMqLqz2BEVS7PDhE',
    appId: '1:12167641124:web:e79ff077c269d795a480b1',
    messagingSenderId: '12167641124',
    projectId: 'quizzapp-d56de',
    authDomain: 'quizzapp-d56de.firebaseapp.com',
    databaseURL: 'https://quizzapp-d56de-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'quizzapp-d56de.appspot.com',
    measurementId: 'G-9CG28C86TV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdBYqBLhy0WCeOKo9MxnB-LhIfyHbKi-A',
    appId: '1:12167641124:android:df8937825e7df790a480b1',
    messagingSenderId: '12167641124',
    projectId: 'quizzapp-d56de',
    databaseURL: 'https://quizzapp-d56de-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'quizzapp-d56de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxNhxy6j9JsA_Vo2Vlr01K2shiHaQED04',
    appId: '1:12167641124:ios:78c46b57fc063bd8a480b1',
    messagingSenderId: '12167641124',
    projectId: 'quizzapp-d56de',
    databaseURL: 'https://quizzapp-d56de-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'quizzapp-d56de.appspot.com',
    iosClientId: '12167641124-iiboodokd1avoo9i65muob3eu6argv1m.apps.googleusercontent.com',
    iosBundleId: 'com.wangyin.od',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxNhxy6j9JsA_Vo2Vlr01K2shiHaQED04',
    appId: '1:12167641124:ios:ce0e17783cc60881a480b1',
    messagingSenderId: '12167641124',
    projectId: 'quizzapp-d56de',
    databaseURL: 'https://quizzapp-d56de-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'quizzapp-d56de.appspot.com',
    iosClientId: '12167641124-o3vbu9jru6tl71ug8edclbole85ebj6g.apps.googleusercontent.com',
    iosBundleId: 'com.wangyin.od.RunnerTests',
  );
}
